<?php

namespace AppBundle\Repository;

/**
 * VideoBookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoBookmarkRepository extends \Doctrine\ORM\EntityRepository
{
}
