# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    RestClientService:
        class: AppBundle\Service\RestClientService
        public: true
        scope: request
    SerializerService:
        class: AppBundle\Service\SerializerService
        public: true
    OembedService:
        class: AppBundle\Service\OembedService
        public: true
